export const categoryData = [
    {
        icon: "A",
        category: "Dinner",
        group: "Food",
        isHidden: "",
        budget: "",
        cashflow: "expense",
    },
    {
        icon: "B",
        category: "Lunch",
        group: "Food",
        isHidden: "",
        budget: "",
        cashflow: "expense",
    },
    {
        icon: "C",
        category: "Tric",
        group: "Transportation",
        isHidden: "",
        budget: "",
        cashflow: "expense",
    },
    {
        icon: "A",
        category: "Salary",
        group: "Work",
        isHidden: "",
        budget: "",
        cashflow: "income",
    },
    {
        icon: "B",
        category: "Bonus",
        group: "Work",
        isHidden: "",
        budget: "",
        cashflow: "income",
    },
    {
        icon: "C",
        category: "salary",
        group: "Part Time Job",
        isHidden: "",
        budget: "",
        cashflow: "income",
    },
]